export const FETCH_STUDENT = 'FETCH_STUDENT';
export const FETCH_INTERVIEW = 'FETCH_INTERVIEW';
export const ADD_INTERVIEW = 'ADD_INTERVIEW';
export const ADD_STUDENT = 'ADD_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';